apiVersion: v1
kind: ConfigMap
metadata:
  name: shoppingapi-configmap
data:
  shoppingapi_url: http://shoppingapi-service   # change here -> removed port number, in case of aks port number is not required