name: CI Build and Push Docker image to Docker HUB

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push docker images
      uses: docker/build-push-action@v4
      with:
        context: Shopping/Shopping.Client/
        push: true
        tags: rahul26s/shoppingapp:latest